# Generated by Django 4.2.3 on 2023-11-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "roll",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("marks", models.IntegerField()),
                ("pass_year", models.IntegerField()),
                ("mobile", models.IntegerField()),
                ("email", models.CharField(max_length=50)),
            ],
        ),
    ]
