# Generated by Django 4.2.3 on 2023-12-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("hod", models.CharField(max_length=50)),
                ("hod_mobile", models.IntegerField()),
                ("hod_email", models.CharField(max_length=50)),
            ],
        ),
    ]
