# Generated by Django 5.0 on 2023-12-08 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.department",
            ),
            preserve_default=False,
        ),
    ]
